{{- if .Values.routes.enabled }}
{{- if .Values.routes.frontend.enabled }}
---
# Route / to frontend service
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.routes.frontend.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
    app: {{ .Values.frontend.name }}
spec:
  parentRefs:
    - name: {{ .Values.routes.gateway.name }}
      namespace: {{ .Values.routes.gateway.namespace }}
      sectionName: https
  hostnames:
    - {{ .Values.routes.frontend.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.routes.frontend.path }}
      backendRefs:
        - kind: Service
          name: {{ .Values.frontend.name }}
          port: {{ .Values.frontend.service.port }}
{{- end }}

{{- if .Values.routes.backend.enabled }}
---
# Route /api to backend service
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.routes.backend.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
    app: {{ .Values.backend.name }}
spec:
  parentRefs:
    - name: {{ .Values.routes.gateway.name }}
      namespace: {{ .Values.routes.gateway.namespace }}
      sectionName: https
  hostnames:
    - {{ .Values.routes.backend.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.routes.backend.path }}
      backendRefs:
        - kind: Service
          name: {{ .Values.backend.name }}
          port: {{ .Values.backend.service.port }}
{{- end }}
{{- end }}
