{{- if .Values.web.enabled }}
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: {{ .Values.web.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  protocol: http
{{- end }}

{{- if .Values.api.enabled }}
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  protocol: http
{{- end }}
