---
# Consul Helm Chart Values for GKE
# Generated by Terraform

global:
  name: consul
  datacenter: ${datacenter}

  # Enable TLS for all Consul communication
  tls:
    enabled: ${enable_tls}
    enableAutoEncrypt: true

  # Enable ACLs for secure access control
  acls:
    manageSystemACLs: ${enable_acls}

# --- Server Configuration ---
server:
  enabled: true
  replicas: ${replicas}
  bootstrapExpect: ${bootstrap_expect}

  serviceAccount:
    annotations: |
      iam.gke.io/gcp-service-account: ${server_iam_sa}

  # Resource requests/limits for production
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

  storage: ${storage_size}
  storageClass: ${storage_class}

  # Pod anti-affinity to spread servers across nodes
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname

# --- Client Configuration ---
# Clients must be disabled on GKE Autopilot as they use
# hostPorts/privileged mode
client:
  enabled: false
  grpc: true

# --- Connect Inject (Service Mesh) ---
connectInject:
  enabled: true
  default: false
  apiGateway:
    manageExternalCRDs: ${manage_crds}
    manageNonStandardCRDs: ${manage_crds}

# --- Consul UI ---
ui:
  enabled: true
  service:
    type: LoadBalancer
    annotations: |
      cloud.google.com/load-balancer-type: "External"
    additionalSpec: |
      loadBalancerSourceRanges: ${allowed_cidrs}
