# Consul Helm Chart Values for GKE
# Generated by Terraform (Consul Helm Chart v1.4.0 compatible)

global:
  name: consul
  datacenter: ${datacenter}
  gcp:
    projectID: ${gcp_project_id}

  # Enable TLS for all Consul communication
  tls:
    enabled: ${enable_tls}
    enableAutoEncrypt: true

  # Enable ACLs for secure access control
  acls:
    manageSystemACLs: ${enable_acls}

  # Enable Prometheus metrics
  metrics:
    enabled: ${enable_metrics}

# --- Server Configuration ---
server:
  enabled: true
  replicas: ${replicas}
  bootstrapExpect: ${bootstrap_expect}

  serviceAccount:
    annotations: |
      iam.gke.io/gcp-service-account: ${server_iam_sa}

  # Resource requests/limits for production
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

  storage: ${storage_size}
  storageClass: ${storage_class}

  # Pod anti-affinity to spread servers across nodes
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname

# --- Client Configuration ---
# Clients must be disabled on GKE Autopilot as they use hostPorts/privileged mode
client:
  enabled: %{ if enable_gke_autopilot }false%{ else }true%{ endif }

# --- Connect Inject (Service Mesh) ---
connectInject:
  enabled: true

  # Set to false to use annotations per-deployment
  default: false

  # GKE-optimized configuration for both Standard and Autopilot
  cni:
    enabled: ${enable_cni}
    logLevel: info
    cniBinDir: "/home/kubernetes/bin"
    cniNetDir: "/etc/cni/net.d"

  # Consul API Gateway configuration
  # GKE already manages standard Gateway API CRDs, so we must disable management here
  apiGateway:
    manageExternalCRDs: false
    manageNonStandardCRDs: false
    managedGatewayClass:
      serviceType: ${api_gateway_service_type}

# --- Consul UI ---
ui:
  enabled: ${enable_ui}
  service:
    type: ${ui_service_type}
